---
title: "COMPSCIX 415.2 Homework 1"
author: "Claude Phan"
date: "2/3/19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

My Github repository for my assignments can be found at this URL: https://github.com/claudephan/compscix-415-2-assignments.git

```{r load_packages, warning=FALSE, message=FALSE}
library(mdsr)
library(tidyverse)

```

```{r}
data("WorldCities")
```

```{r}
glimpse(WorldCities)
```

Question 1: There are 23,018 observations in the data set. Some of the variable names name, region, country, and date.


```{r}
WorldCities <- head(WorldCities, 200) # 200 rows
country_col <- WorldCities$country
unique(country_col)
```

```{r}
region_col <- WorldCities$region
unique(region_col)
```
Question 2: Above are the unique values for region column.
```{r}
WorldCities %>% select(country) %>% unique()
```
Question 3: Unique entries from the country column
```{r}
WorldCities %>% ggplot(aes(x = population)) + geom_histogram()
```

```{r}
WorldCities %>% ggplot(aes(x = population)) +
  geom_histogram() +
  xlab('City Population') +
  ylab('Counts') +
  ggtitle('Distribution of City Populations') +
  theme_bw()
```

